// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apnbtqpoliqyqulcoldw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwbmJ0cXBvbGlxeXF1bGNvbGR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NzIwMTUsImV4cCI6MjA1NjQ0ODAxNX0.fpgh7MRgcJjReIDYD6gSR4NWRtHzLHA9nQ8uMRA3tYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);